#! /bin/bash
pkg="etcd-aws-proxy"
version="0.4"
etcd_peers_file_path="/etc/sysconfig/etcd-peers"
etcd_initial_cluster_file_path="/etc/sysconfig/initial-cluster"
# Upload to S3 bucket. Either pass in as S3BUCKET or generate one from AWS account name. 
account=$(aws --region $region autoscaling describe-auto-scaling-groups --auto-scaling-group-names=$ASGNAME \
          | jq ".AutoScalingGroups[].AutoScalingGroupARN" | cut -d":" -f5)
discovery_bucket=${S3BUCKET:-"s3://${account}-coreos-cluster-cloudinit"}


if [[ ! $etcd_peers_file_path ]]; then
    echo "$pkg: $$etcd_peers_file_path doesn't exist."
    exit 4
else
    if  etcd_initial_cluster=$(grep ETCD_INITIAL_CLUSTERR= $etcd_peers_file_path) ; 
    then 
        echo $etcd_initial_cluster
    else
        echo "$pkg: $$etcd_peers_file_path doesn't exist."
        exit 4
    fi
fi
echo "ETCD_INITIAL_CLUSTER=$etcd_initial_cluster" > $etcd_initial_cluster_file_path

if ! aws --region $region s3 ls $discovery_bucket > /dev/null 2>&1 ;
then
  aws --region $region s3 mb $discovery_bucket 
fi
aws --region $region s3 cp $etcd_initial_cluster_file_path $discovery_bucket/etcd/$(basename $etcd_initial_cluster_file_path)
